import { useEffect, useState } from 'react';
import { useApp } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import api from '../api';
import { fmtDMY } from '../utils/date';

// Matches the reference prototype's flat rowspan table: one NFA can have
// zero, one, or many order rows; the NFA/date/project/desc/vendor/value/
// MC-comment/generate-control cells rowspan across all its order rows.
export default function Page4() {
  const { isAdmin, role } = useApp();
  const { push } = useToast();

  const [nfaGroups, setNfaGroups] = useState([]); // [{ nfa, index, date, project, desc, vendor, val, mcComment, orders: [...] }]
  const [maxOrders, setMaxOrders] = useState(10);
  const [loading, setLoading] = useState(false);
  const [q, setQ] = useState('');
  const [deleteTarget, setDeleteTarget] = useState(null);

  async function load() {
    setLoading(true);
    try {
      const cfg = await api.ordersConfig();
      setMaxOrders(Number(cfg.maxOrdersPerNfa || 10));
      const approved = await api.approvedNfas();
      setNfaGroups(approved.map((e) => ({
        nfa: e.nfa, index: e.index, date: e.approvedOn, project: e.project, desc: e.desc,
        vendor: e.vendor, val: e.val, mcComment: e.mcComment, orders: e.orders,
      })));
    } catch (e) { push(e.response?.data?.error || 'Failed to load orders', 'error'); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, []);

  const qLower = q.toLowerCase();
  const filtered = nfaGroups.filter((n) => {
    if (!qLower) return true;
    const hay = `${n.nfa} ${n.desc} ${n.vendor} ${n.orders.map((o) => `${o.OrderNo} ${o.Vendor}`).join(' ')}`.toLowerCase();
    return hay.includes(qLower);
  });

  return (
    <div className="pagewrap">
      <div className="surface">
        <div className="toolbar">
          <input className="inp" style={{ width: 250 }} placeholder="Search NFA no. / order no. / vendor…" value={q} onChange={(e) => setQ(e.target.value)} />
          <span className="filterlbl">Show: {role === 'user' ? 'My approved NFAs' : 'All approved NFAs'}</span>
          <span className="filterlbl">Meeting date: All</span>
          <div className="spacer" />
          <span className="filterlbl">
            Max orders per NFA: {isAdmin ? (
              <input className="inp" style={{ width: 48, padding: '3px 5px' }} value={maxOrders}
                onChange={async (e) => {
                  const v = Number(e.target.value) || 1;
                  setMaxOrders(v);
                  try { await api.setMaxOrders(v); } catch { push('Failed to update', 'error'); }
                }} />
            ) : <b>{maxOrders}</b>} (admin)
          </span>
        </div>

        {loading ? <div className="empty">Loading…</div> : filtered.length === 0 ? (
          <div className="empty">No approved NFAs yet{role === 'user' ? ' for you' : ''}. Approvals appear here after Publish on Page 3.</div>
        ) : (
          <div className="tablewrap">
            <table>
              <thead>
                <tr>
                  <th>NFA No.</th><th>Approved On</th><th>Project</th><th>Description of Work</th>
                  <th>Vendor(s) per NFA</th><th>Value ₹L</th><th>MC Comments</th><th>No. of Orders → Generate</th>
                  <th>Order No.</th><th>Vendor / Supplier / Contractor (per order)</th><th>Order Type</th><th>Generated By</th><th></th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((n) => (
                  <NfaOrderRows key={n.nfa} entry={n} maxOrders={maxOrders} onRefresh={load} onDeleteRequest={setDeleteTarget} />
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {deleteTarget && (
        <div className="mback" onClick={(e) => { if (e.target === e.currentTarget) setDeleteTarget(null); }}>
          <div className="modal">
            <h3>Delete order number?</h3>
            <p>
              Order <b>{deleteTarget.OrderNo}</b> ({deleteTarget.NfaNo}{deleteTarget.Vendor ? `, ${deleteTarget.Vendor}` : ''}) will be retired,
              not reused, and the deletion is audit-logged. Any PO/SO already issued in QMS against it must be voided there separately.
            </p>
            <div className="actions">
              <button className="btn ghost" onClick={() => setDeleteTarget(null)}>Keep order number</button>
              <button className="btn danger" onClick={async () => {
                try {
                  await api.deleteOrder(deleteTarget.Id);
                  push(`Order number ${deleteTarget.OrderNo} deleted — retired & audited`, 'warn');
                  setDeleteTarget(null);
                  load();
                } catch (e) { push(e.response?.data?.error || 'Delete failed', 'error'); }
              }}>Delete order number</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function NfaOrderRows({ entry, maxOrders, onRefresh, onDeleteRequest }) {
  const { push } = useToast();
  const [count, setCount] = useState(1);
  const hasOrders = entry.orders.length > 0;
  const span = entry.orders.length || 1;

  async function generate() {
    try {
      await api.generateOrders({ nfa: entry.nfa, index: entry.index, count, orderType: 'PO' });
      push(`Order number generated for ${entry.nfa}`);
      onRefresh();
    } catch (e) { push(e.response?.data?.error || 'Generate failed', 'error'); }
  }
  async function addMore() {
    if (!window.confirm(`Add ${count} more order number(s) against ${entry.nfa}? Existing order rows stay untouched.`)) return;
    try {
      await api.addMoreOrders({ nfa: entry.nfa, index: entry.index, count, orderType: 'PO' });
      push(`Order number(s) generated for ${entry.nfa}`);
      onRefresh();
    } catch (e) { push(e.response?.data?.error || 'Failed', 'error'); }
  }
  async function override(order, newValue) {
    try { await api.overrideOrder(order.Id, newValue); onRefresh(); }
    catch (e) { push(e.response?.data?.error || 'Override failed', 'error'); onRefresh(); }
  }

  const leadCells = (
    <>
      <td className="nfa" rowSpan={span}>{entry.nfa}</td>
      <td rowSpan={span}>{fmtDMY(new Date(entry.date).toISOString().slice(0, 10))}</td>
      <td rowSpan={span}>{entry.project}</td>
      <td rowSpan={span}>{entry.desc}{entry.mcComment && <div className="sub">MC comment: {entry.mcComment}</div>}</td>
      <td rowSpan={span}>{entry.vendor}</td>
      <td rowSpan={span}><b>{entry.val}</b></td>
      <td rowSpan={span}>{entry.mcComment || '—'}</td>
      <td rowSpan={span}>
        <div style={{ display: 'flex', gap: 5, alignItems: 'center', flexWrap: 'wrap' }}>
          <select className="inp" style={{ width: 58 }} value={count} onChange={(e) => setCount(Number(e.target.value))}>
            {Array.from({ length: maxOrders }, (_, i) => i + 1).map((n) => <option key={n} value={n}>{n}</option>)}
          </select>
          <button className="btn sm primary" onClick={hasOrders ? addMore : generate}>
            {hasOrders ? `Add ${count} more order${count > 1 ? 's' : ''}` : 'Generate order number'}
          </button>
        </div>
        {hasOrders && <div className="sub">{entry.orders.length} order row{entry.orders.length > 1 ? 's' : ''} created ↓</div>}
      </td>
    </>
  );

  if (!hasOrders) {
    return <tr>{leadCells}<td className="st grey" colSpan={5}>—</td></tr>;
  }

  return (
    <>
      {entry.orders.map((o, i) => (
        <tr key={o.Id}>
          {i === 0 && leadCells}
          <td>
            <input className="inp nfa" style={{ width: 158, fontWeight: 700 }} defaultValue={o.OrderNo}
              onBlur={(e) => override(o, e.target.value)} />
            {o.IsOverride
              ? <div className="sub" style={{ color: '#9A6700' }}>manual override · audited</div>
              : <div className="sub">interim format — syntax pack pending</div>}
          </td>
          <td className="edit">
            <input className="inp" style={{ width: '100%', background: 'transparent', border: 'none' }} placeholder="Type vendor name…"
              defaultValue={o.Vendor} onBlur={async (e) => { await api.setVendor(o.Id, e.target.value); onRefresh(); }} />
          </td>
          <td>
            <select className="inp" defaultValue={o.OrderType} onChange={async (e) => { await api.setOrderType(o.Id, e.target.value); onRefresh(); }}>
              {['PO', 'SO', 'WO', 'LOA'].map((t) => <option key={t} value={t}>{t}</option>)}
            </select>
          </td>
          <td>{o.GeneratedBy} · {new Date(o.GeneratedAt).toLocaleString()}</td>
          <td style={{ whiteSpace: 'nowrap' }}>
            <span className="st grey">register ✓</span>
            <button className="ordel" title="Delete this order number" onClick={() => onDeleteRequest(o)}>Delete ✕</button>
          </td>
        </tr>
      ))}
    </>
  );
}
